### ISSUE TITLE
Server Won't Start - ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by SterlingButters** [XD-DENG/minimalcluster-py#4]
Why could I be getting this error? Is it because the server won't start? Also, why won't the server start?

Please see code:

```
import multiprocessing
from minimalcluster import MasterNode
import socket


def get_open_port():
    import socket
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind((str(socket.gethostname()), 0))
    s.listen(1)
    port = s.getsockname()[1]
    s.close()
    return port


def main():
    # host_ip = str(socket.gethostbyname(socket.gethostname()))
    # host_ip = str("0.0.0.0")
    host_ip = socket.gethostname()
    print(host_ip)
    # Find open Port
    your_port = get_open_port()
    your_authkey = 'ABC123'

    master = MasterNode(HOST=host_ip, PORT=your_port, AUTHKEY=your_authkey)
    server = master.start_master_server()

    # worker = WorkerNode(host_ip, your_port, your_authkey, nprocs=N_processors_to_use)
    # worker.join_cluster()

    workers = master.list_workers()
    print('Server:', server)
    print('Workers:', workers)

    envir_statement = '''f = lambda x:x[0]+x[1]
    '''
    master.load_envir(envir_statement, from_file=False)
    master.register_target_function("f")

    master.load_args([(1, 2), (3, 4), (5, 6), (7, 8)])

    result = master.execute()

    print(result)
    # print(multiprocessing.cpu_count())


if __name__ == '__main__':
    main()
```

Please see Traceback:

```
C:\ProgramData\Anaconda3\python.exe "C:/Users/Sterling Butters/PycharmProjects/MinimalCluster/Test.py"
DESKTOP-ICOTGB3
[2018-01-21 18:03:17.913562] Master Node started at DESKTOP-ICOTGB3:54592 with authkey `ABC123`.
[INFO] Current node has joined the cluster as a Worker Node (using 28 processors; Process ID: 30248).
Server: None
Workers: [('DESKTOP-ICOTGB3', 28, 30356, 0)]
[2018-01-21 18:03:20.972855] Assigning jobs to worker nodes.
[2018-01-21 18:03:20.986033] Started working on some tasks.
[2018-01-21 18:03:22.381736] Tasks finished.
[2018-01-21 18:03:22.508374] Aggregating on Master node...
{(1, 2): 3, (3, 4): 7, (5, 6): 11, (7, 8): 15}
Process Process-2:1:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\minimalcluster\worker_node.py", line 63, in heartbeat
    if not queue_of_worker_list.empty():
  File "<string>", line 2, in empty
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Process Process-2:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\minimalcluster\master_node.py", line 52, in start_worker_in_background
    worker.join_cluster()
  File "C:\ProgramData\Anaconda3\lib\site-packages\minimalcluster\worker_node.py", line 154, in join_cluster
    if_job_q_empty = self.job_q.empty()
  File "<string>", line 2, in empty
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\managers.py", line 756, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\connection.py", line 368, in _send
    n = write(self._handle, buf)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Process finished with exit code 0
```

**Comment by XD-DENG** [comment]
Hi @SterlingButters , thanks for the feedback!

Actually the job was successfully finished, as indicated by the rows in your Traceback,

```
[2018-01-21 18:03:22.508374] Aggregating on Master node...
{(1, 2): 3, (3, 4): 7, (5, 6): 11, (7, 8): 15}
```

You encountered this error as your script keeps waiting after all jobs are finished. The server side would close the connection after waiting for too long, which the client side would try to re-use it (https://stackoverflow.com/questions/8814802/python-errno-10054-an-existing-connection-was-forcibly-closed-by-the-remote-h).

I would suggest either
[1] Go ahead to the other workload after `master.execute()`;
[2] Properly shutdown the cluster by invoking `master.shutdown`, or properly close your program.

For example, you would not encounter this error anymore if you add row `master.shutdown` at the end of your `main()` function.

Kindly let me know if this clarifies. Thanks!

**Comment by SterlingButters** [comment]
Ahhh so the server side is closing because of timeout since all jobs are completed? So is the value of server being 'None' normal? Why is that?

Thanks so much for your help and quick response!

**Comment by SterlingButters** [comment]
Also real quick: since I don't see in the docs, is there a need to pass files to a worker node if the dependencies of the envir_statement include said files? If so, how?

EDIT: Wow I'm impressed, it pulls everything that's needed from the envir_file. (though I am running solely on host right now so hopefully that won't change once I get the other worker nodes connected.)

**Comment by XD-DENG** [comment]
Hi @SterlingButters , please find my opinions as below.

**For your questions 1, value of server being "None"**: Your `server` value comes from the line below 
```
server = master.start_master_server()
```

`master.start_master_server()` doesn't return any value, that's why your "server" value is None. This is normal.

**For your question 2**: similar to many other distributed framework (like `Spark`), `minimalcluster` doesn't help pass files. The common method is to store your file with a distributed storage system, like HDFS, then all your nodes can access the file in the same way (say using the same path).

**Comment by XD-DENG** [comment]
Hi @SterlingButters , for your comment "*it pulls everything that's needed from the envir_file. (though I am running solely on host right now so hopefully that won't change once I get the other worker nodes connected.)*": this package is able to handle & pass everything you stated in your envir_file. But if you're invoking any external file or data inside your envir_file, I think you will encounter error like "file or path not found". That's why I say you'll need a distributed storage system like HDFS.

**Comment by SterlingButters** [comment]
Thank you so much for your answers, I will close issue
